# Generated by Django 5.0.4 on 2024-05-05 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_rename_bill_id_billdetail_billid_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='billdetail',
            table='billdetail',
        ),
        migrations.AlterModelTable(
            name='clientdetail',
            table='clientdetail',
        ),
        migrations.AlterModelTable(
            name='paymentdetail',
            table='paymentdetail',
        ),
        migrations.AlterModelTable(
            name='productdetail',
            table='productdetail',
        ),
        migrations.AlterModelTable(
            name='userdetail',
            table='userdetail',
        ),
    ]
